name: Build and Release Electron App
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build Electron App
        run: npm run make

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: ./out/make

  release:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: release
          path: ./out/make

      - name: List Contents of GitHub Workspace
        run: Get-ChildItem -Path ${{ github.workspace }}

      - name: Read App Version
        id: version
        run: |
          $packageJson = Get-Content -Raw -Path "${env:GITHUB_WORKSPACE}/package.json"
          $version = ($packageJson | ConvertFrom-Json).version
          echo "::set-output name=app_version::$version"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.app_version }}
          release_name: Release v${{ steps.version.outputs.app_version }}
          draft: false
          prerelease: false
