name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.7.1'  # Use the Node.js version required by your project

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build -- --prod  # Build the Angular project in production mode

    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: ./dist/pUIng/*  # This should match the output directory of your Angular build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write  # Allows deployment to GitHub Pages
      id-token: write  # Required for GitHub Pages authentication
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: build-artifact
        path: ./dist/pUIng/*  # Ensure this matches the path used in the build job

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        branch: gh-pages  # Deploy to the gh-pages branch
        folder: ./dist  # This is the directory to deploy
