name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.7.1'  # Use the Node.js version required by your project

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build -- --prod  # Build the Angular project in production mode

    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: ./dist  # This should match the output directory of your Angular build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write  # Allows deployment to GitHub Pages
      id-token: write  # Required for GitHub Pages authentication
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: build-artifact
        path: ./dist  # Ensure this matches the path used in the build job

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m 'Deploy to GitHub Pages'
        git push origin `gh-pages` --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


# name: Deploy to GitHub Pages

# on:
#   push:
#     branches:
#       - master  # Trigger the workflow on push to the master branch

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Setup Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '21.7.1'  # Use the Node.js version required by your project

#     - name: Install dependencies
#       run: npm install

#     - name: Build the project
#       run: npm run build -- --prod  # Build the Angular project in production mode

#     - name: Deploy to GitHub Pages
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: ./pUIng/dist/pUIng  # This is the output directory of your build command
