name: Release Electron App
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build Electron App
        run: npm run make
        working-directory: .
  release:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Upload release artifact
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: ./out/make
      - name: List Contents of GitHub Workspace
        run: |
            Get-ChildItem -Path ${{ github.workspace }}
      - name: Get Package Version
        run: |
            $version = npm pkg get version --workspaces=false
            $version = $version.Replace('"', '')
            echo "::set-output name=app_version::$version"          
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.app_version }}
          release_name: Release v${{ steps.version.outputs.app_version }}
          draft: false
          prerelease: false
